apiVersion: v1
kind: Service
metadata:
  name: devops-application-service
spec:
  selector:
    app: devops-application
  ports:
    - port: 9090   # Service'in dinleyeceği port
      targetPort: 8080   # Pod içindeki .jar uygulamanın portu - containerPort ile aynı olmalı
  type: NodePort    # Service tipi (ClusterIP, NodePort, LoadBalancer, vb.)
